### ISSUE TITLE
Drop Where condition

### ISSUE THREAD

**Issue by KurnakovMaksim** [KurnakovMaksim/jiraF-goal#37]
GoalModel.EditLabel:
``` cs
bool containsLabel = availableLabels
    .Where(x => x.Title.Value == label).Any();
```
Transfer where condition to any.

**Comment by Saad-Ali-Shaikh** [comment]
bool containsLabel = availableLabels
    .Any(x => x.Title.Value == label);

**Comment by KurnakovMaksim** [comment]
@Saad-Ali-Shaikh your right, can you refactor it?
